version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - "some-net"
  redis:
    image: redis
    networks:
      - "some-net"

networks:
  some-net:
    driver: bridge